### ISSUE TITLE
Initial Release (v0.11.0)

### ISSUE THREAD

**Issue by hanny-ph** [sujrd/faiadashu#77]
We need to create a release so it's easier for other project versioning.

But we need to wait for the following issues to be addressed:
- [x] https://github.com/sujrd/faiadashu/issues/68
- [x] https://github.com/sujrd/faiadashu/issues/69

**Comment by hanny-ph** [comment]
@fjwong @ajsviado @juakotorres 

This will be an initial release of faiadashu in our repo, if you guys have issues that want to be included in this release. please let us know!

Thank you!

**Comment by fjwong** [comment]
Thanks @hanny-ph. For now, I don't think we have any issues blocking the release.

About the versioning, it seems the original project was following the same numbering as the `fhir` package, which is currently at `v0.11.0`. I don't know if we'd like to preserve this convention, or start anew from v1.0.0.

**Comment by juakotorres** [comment]
@hanny-ph Thanks a lot for this, it will help a lot!

**Comment by hanny-ph** [comment]
> it seems the original project was following the same numbering as the fhir package, which is currently at v0.11.0.

Sorry, I was not aware that `faiadashu` follows that convention.

IMO, it would be better to use that convention since this package is tightly coupled with `fhir`.
